### PR TITLE
gh-31 Add initial draft of Tags element to BaseObjectGroup

### PR DESCRIPTION
**Pull request by at055612**
Address #31 and #37 

Still requires some example values in the annotations.

### CODE REVIEW

**Comment by burnalting** [comment]
Suggested documentation:

Information stored in repositories can be categorised (or tagged) with keywords or phrases that  allow users to group or filter information labelled the same tags. Examples of this concept can be found in
- a corporate document repository where users can tag documents with one or more keywords that allow search filtering such as `Finance`, `Purchases`, `Human-resources`, `Payroll`, `Sales`, `Domestic-sales`, `International-sales`, `Research`, `ICT`, `ICT-Sustainment`, etc.
- a web-based hosting service such as [GitHub](https://github.com). In this case, one can categorise projects with topics. For example, the [GCHQ Stroom](https://github.com/gchq/stroom) project is categorised with the topics `xslt`, `lucene`, `big-data`, `pipeline-processor`, `data-analytics`, `enrichment`, `visualisation` and `dashboards`.
- the [Apple](https://www.apple.com) macOS and [iCloud](https://www.icloud.com/) file tag mechanism that allows one to organise and sort files using tags within the Finder application. 
- [Flickr](https://www.flickr.com) tags that allow users or Flickr's image recognition software to associate tags with images that help users find similar images in a search.

**Comment by at055612** [comment]
I have backported what we have in the on-site schema.  I have enforced UPPER_SNAKE_CASE for the tags.  Possibly a mistake as lower-hyphen-case seems more common for this sort of thing but a precedent has already been set on site. Also created a TagSimpleType so it can be reused in multiple places.

**Comment by burnalting** [comment]
We **cannot** enforce any enumeration on the tags as we are just copying data from an event source. The event source dictates the content such as this, not the event storage capability. If we force an enumeration, we are changing audit data which is not appropriate.
The only enforcement we can make is that it is a string and not null, but one assumes .+ is pointless.

This is a similar situation to the EmailAddressSimpleType ... a user can type in any address and our event just records what is given.

**Comment by at055612** [comment]
Fair point @burnalting about taking takes from the event source.  I had in my head that they would be tags added either post receipt with decoration, during translation or when an xml event is crafted by the client system.  In your case a restriction would be unhelpful.  I will change to just a string and leave the content down to local convention.

**Comment by burnalting** [comment]
Thanks.

**Pull request merged**
